<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UProjectHubVersion>0.3.1</UProjectHubVersion>
    <Version>$(UProjectHubVersion)</Version>
    <AssemblyVersion>$(UProjectHubVersion).0</AssemblyVersion>
    <FileVersion>$(UProjectHubVersion).0</FileVersion>
    <InformationalVersion>$(UProjectHubVersion) r</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UProjectHub.Core\UProjectHub.Core.csproj" />
    <ProjectReference Include="..\UProjectHub.Windows\UProjectHub.Windows.csproj" />
  </ItemGroup>

</Project>
